const MOCK_TODAY_MATCHES = [
  {
    id: 1,
    league: "ENGLISH PREMIER LEAGUE",
    kickoff: "21:00 WIB",
    homeTeam: "Arsenal",
    awayTeam: "Brighton",
    homeForm: ["W","W","W","D","W"],
    awayForm: ["W","D","L","W","L"],
    pick: "Arsenal Menang (1X2)",
    marketType: "1X2",
    odds: 1.62,
    winProb: 78,
    isVip: false,
    posEdge: "+18.2% +EV (Keunggulan xG Kandang)",
    riskFactor: "-4.1% Volatilitas Serangan Balik",
    metrics: { form: 88, h2h: 82, xG: 79, marketVal: 85 },
    aiNotes: "Arsenal mencatatkan rerata xG 2.3 di Stadion Emirates. Perhitungan probabilitas Poisson menunjukkan keunggulan penguasaan bola kandang mendominasi."
  },
  {
    id: 2,
    league: "SPANISH LA LIGA",
    kickoff: "22:15 WIB",
    homeTeam: "Real Madrid",
    awayTeam: "Real Betis",
    homeForm: ["W","W","D","W","W"],
    awayForm: ["D","W","L","D","W"],
    pick: "Over 2.5 Gol",
    marketType: "OU",
    odds: 1.58,
    winProb: 75,
    isVip: false,
    posEdge: "+15.6% +EV (Efisiensi Tembakan High-Zone)",
    riskFactor: "-6.2% Risiko Pertahanan Rapat",
    metrics: { form: 84, h2h: 80, xG: 82, marketVal: 78 },
    aiNotes: "Indikator tembakan tepat sasaran kedua tim konsisten tinggi. Matriks data 8 dari 10 laga terakhir menghasilkan akumulasi gol di atas 2.5."
  },
  {
    id: 3,
    league: "GERMAN BUNDESLIGA",
    kickoff: "23:30 WIB",
    homeTeam: "Bayer Leverkusen",
    awayTeam: "Wolfsburg",
    homeForm: ["W","W","W","W","D"],
    awayForm: ["L","D","W","L","L"],
    pick: "Leverkusen -1.0 HDP",
    marketType: "HDP",
    odds: 1.72,
    winProb: 76,
    isVip: false,
    posEdge: "+21.0% +EV (Dominasi Area Bahaya 64%)",
    riskFactor: "-3.5% Rotasi Pemain Sayap",
    metrics: { form: 92, h2h: 85, xG: 88, marketVal: 82 },
    aiNotes: "Rata-rata penguasaan zona penalti musuh oleh Leverkusen mencapai 64%. Rasio pergerakan value odds menunjukkan proyeksi keunggulan selisih gol tebal."
  },
  {
    id: 4,
    league: "ITALIAN SERIE A",
    kickoff: "00:00 WIB",
    homeTeam: "Inter Milan",
    awayTeam: "Atalanta",
    homeForm: ["W","D","W","W","W"],
    awayForm: ["W","W","D","L","W"],
    pick: "Over 2.5 Gol",
    marketType: "OU",
    odds: 1.68,
    winProb: 72,
    isVip: false,
    posEdge: "+12.8% +EV (Indeks Kombinasi xG 3.12)",
    riskFactor: "-8.0% Kebobolan Bola Mati",
    metrics: { form: 80, h2h: 75, xG: 84, marketVal: 76 },
    aiNotes: "Struktur taktikal menyerang terbuka kedua tim terbukti menghasilkan indeks expected goals (xG) gabungan sebesar 3.12 gol per laga."
  },
  {
    id: 5,
    league: "DUTCH EREDIVISIE",
    kickoff: "01:00 WIB",
    homeTeam: "PSV Eindhoven",
    awayTeam: "FC Utrecht",
    homeForm: ["W","W","W","W","W"],
    awayForm: ["D","L","W","D","L"],
    pick: "PSV -1.25 HDP",
    marketType: "HDP",
    odds: 1.80,
    winProb: 74,
    isVip: true,
    posEdge: "+24.5% +EV (Rekor 12 Win Kandang)",
    riskFactor: "-2.1% Volatilitas Transisi",
    metrics: { form: 95, h2h: 88, xG: 90, marketVal: 80 },
    aiNotes: "PSV memenangkan 12 laga kandang berturut-turut dengan rerata selisih gol 2.4 per pertandingan berdasarkan data statistik murni."
  },
  {
    id: 6,
    league: "FRENCH LIGUE 1",
    kickoff: "02:00 WIB",
    homeTeam: "PSG",
    awayTeam: "Lille",
    homeForm: ["W","W","D","W","W"],
    awayForm: ["W","D","D","W","L"],
    pick: "PSG Menang (1X2)",
    marketType: "1X2",
    odds: 1.55,
    winProb: 79,
    isVip: true,
    posEdge: "+17.0% +EV (Akurasi Operan Progresif)",
    riskFactor: "-5.0% Potensi Kartu Merah",
    metrics: { form: 86, h2h: 82, xG: 80, marketVal: 84 },
    aiNotes: "Kelengkapan skuad dan data efisiensi operan PSG menghasilkan probabilitas kemenangan matematis di angka 79%."
  },
  {
    id: 7,
    league: "ENGLISH CHAMPIONSHIP",
    kickoff: "02:45 WIB",
    homeTeam: "Leeds United",
    awayTeam: "Hull City",
    homeForm: ["W","W","W","D","W"],
    awayForm: ["L","L","D","W","L"],
    pick: "Leeds Menang (1X2)",
    marketType: "1X2",
    odds: 1.60,
    winProb: 73,
    isVip: true,
    posEdge: "+14.2% +EV (Kebobolan Terendah Elland Road)",
    riskFactor: "-7.1% Efisiensi Penyelesaian Akhir",
    metrics: { form: 82, h2h: 78, xG: 75, marketVal: 72 },
    aiNotes: "Stadion Elland Road memegang rerata kebobolan terendah di divisi liga musim ini berdasarkan metrik defensif."
  },
  {
    id: 8,
    league: "PORTUGUESE PRIMEIRA LIGA",
    kickoff: "03:15 WIB",
    homeTeam: "Benfica",
    awayTeam: "Moreirense",
    homeForm: ["W","W","W","W","D"],
    awayForm: ["L","D","W","L","D"],
    pick: "Over 2.5 Gol",
    marketType: "OU",
    odds: 1.65,
    winProb: 71,
    isVip: true,
    posEdge: "+11.9% +EV (Persentil 95% Konversi Shots)",
    riskFactor: "-6.8% Tempo Bermain Lambat",
    metrics: { form: 85, h2h: 80, xG: 82, marketVal: 75 },
    aiNotes: "Rasio konversi tembakan tepat sasaran Benfica berada pada persentil 95% di liga lokal."
  },
  {
    id: 9,
    league: "SPANISH LA LIGA",
    kickoff: "03:30 WIB",
    homeTeam: "Atletico Madrid",
    awayTeam: "Espanyol",
    homeForm: ["W","D","W","W","W"],
    awayForm: ["L","L","D","L","W"],
    pick: "Atletico -1.0 HDP",
    marketType: "HDP",
    odds: 1.75,
    winProb: 75,
    isVip: true,
    posEdge: "+19.8% +EV (Matriks Pertahanan xGA 0.4)",
    riskFactor: "-3.0% Risiko Skor Tipis 1-0",
    metrics: { form: 88, h2h: 84, xG: 81, marketVal: 79 },
    aiNotes: "Matriks pertahanan Atletico Madrid mencatatkan angka xGA (Expected Goals Against) hanya 0.4 per match."
  },
  {
    id: 10,
    league: "ARGENTINA LIGA PROFESIONAL",
    kickoff: "05:00 WIB",
    homeTeam: "River Plate",
    awayTeam: "San Lorenzo",
    homeForm: ["W","W","D","W","W"],
    awayForm: ["D","L","D","W","L"],
    pick: "River Plate Menang (1X2)",
    marketType: "1X2",
    odds: 1.52,
    winProb: 77,
    isVip: true,
    posEdge: "+16.1% +EV (Dominasi Ball-Possession)",
    riskFactor: "-4.5% Volatilitas Pelanggaran Taktis",
    metrics: { form: 83, h2h: 79, xG: 78, marketVal: 74 },
    aiNotes: "Korelasi dominasi aliran bola di area lawan memberikan River Plate nilai ekspektasi positif (+EV) yang stabil."
  }
];

const MOCK_HISTORY_LOGS = [
  { date: "23 Sep", league: "UEFA Champions League", match: "Man City vs Inter Milan", pick: "Over 2.5 Gol", odds: 1.65, score: "3 - 1", status: "WIN" },
  { date: "23 Sep", league: "UEFA Champions League", match: "Real Madrid vs Stuttgart", pick: "Real Madrid Menang", odds: 1.55, score: "3 - 1", status: "WIN" },
  { date: "23 Sep", league: "UEFA Champions League", match: "Bayern Munich vs Zagreb", pick: "Bayern -1.5 HDP", odds: 1.70, score: "9 - 2", status: "WIN" },
  { date: "22 Sep", league: "English Premier League", match: "Man City vs Arsenal", pick: "Over 2.5 Gol", odds: 1.72, score: "2 - 2", status: "WIN" },
  { date: "22 Sep", league: "Spanish La Liga", match: "Villarreal vs Barcelona", pick: "Over 2.5 Gol", odds: 1.58, score: "1 - 5", status: "WIN" },
  { date: "22 Sep", league: "Italian Serie A", match: "Inter Milan vs AC Milan", pick: "Inter Menang", odds: 1.62, score: "1 - 2", status: "LOST" },
  { date: "21 Sep", league: "German Bundesliga", match: "Eintracht vs M'gladbach", pick: "Over 2.5 Gol", odds: 1.60, score: "2 - 0", status: "LOST" },
  { date: "21 Sep", league: "French Ligue 1", match: "Reims vs PSG", pick: "PSG Menang", odds: 1.50, score: "1 - 1", status: "LOST" },
  { date: "21 Sep", league: "Spanish La Liga", match: "Real Madrid vs Espanyol", pick: "Real Madrid -1.25", odds: 1.68, score: "4 - 1", status: "WIN" },
  { date: "20 Sep", league: "English Premier League", match: "West Ham vs Chelsea", pick: "Over 2.5 Gol", odds: 1.65, score: "0 - 3", status: "WIN" }
];
