const matchesData = [
  {
    id: 1,
    league: "UEFA Champions League",
    time: "03:00 WIB",
    status: "Upcoming",
    homeTeam: "Real Madrid",
    awayTeam: "Manchester City",
    homeLogo: "https://crests.football-data.org/86.svg",
    awayLogo: "https://crests.football-data.org/65.svg",
    probHome: "42%",
    probDraw: "26%",
    probAway: "32%",
    xGHome: "1.85",
    xGAway: "1.62",
    recommendation: {
      market: "Over/Under",
      pick: "Over 2.5 Goals",
      odds: "1.72",
      probability: "78.4%",
      confidence: "High",
      type: "OU"
    },
    reasoning: "Kedua tim memiliki rerata xG gabungan di atas 3.4. Efisiensi konversi peluang dalam 5 laga terakhir mencapai 22%."
  },
  {
    id: 2,
    league: "English Premier League",
    time: "21:00 WIB",
    status: "Upcoming",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    homeLogo: "https://crests.football-data.org/57.svg",
    awayLogo: "https://crests.football-data.org/61.svg",
    probHome: "58%",
    probDraw: "24%",
    probAway: "18%",
    xGHome: "2.10",
    xGAway: "0.95",
    recommendation: {
      market: "1X2",
      pick: "Home Win (Arsenal)",
      odds: "1.65",
      probability: "74.1%",
      confidence: "High",
      type: "1X2"
    },
    reasoning: "Dominasi penguasaan area sepertiga akhir lawan (71%) dan catatan kebobolan tandang Chelsea yang memburuk."
  },
  {
    id: 3,
    league: "Italian Serie A",
    time: "23:30 WIB",
    status: "Upcoming",
    homeTeam: "Inter Milan",
    awayTeam: "Juventus",
    homeLogo: "https://crests.football-data.org/108.svg",
    awayLogo: "https://crests.football-data.org/109.svg",
    probHome: "48%",
    probDraw: "30%",
    probAway: "22%",
    xGHome: "1.55",
    xGAway: "0.90",
    recommendation: {
      market: "Asian Handicap",
      pick: "Inter Milan -0.5",
      odds: "1.88",
      probability: "71.2%",
      confidence: "Medium",
      type: "HDP"
    },
    reasoning: "Rekor pertahanan kandang Inter yang solid dengan hanya membiarkan lawan mencatatkan 0.7 xGA per 90 menit."
  },
  {
    id: 4,
    league: "Spanish La Liga",
    time: "02:00 WIB",
    status: "Upcoming",
    homeTeam: "FC Barcelona",
    awayTeam: "Atletico Madrid",
    homeLogo: "https://crests.football-data.org/81.svg",
    awayLogo: "https://crests.football-data.org/78.svg",
    probHome: "51%",
    probDraw: "27%",
    probAway: "22%",
    xGHome: "1.90",
    xGAway: "1.10",
    recommendation: {
      market: "Over/Under",
      pick: "Over 2.5 Goals",
      odds: "1.80",
      probability: "72.8%",
      confidence: "High",
      type: "OU"
    },
    reasoning: "Gaya bermain garis pertahanan tinggi Barcelona rentan terhadap serangan balik cepat Atletico Madrid."
  },
  {
    id: 5,
    league: "German Bundesliga",
    time: "20:30 WIB",
    status: "Upcoming",
    homeTeam: "Bayern Munich",
    awayTeam: "Bayer Leverkusen",
    homeLogo: "https://crests.football-data.org/5.svg",
    awayLogo: "https://crests.football-data.org/3.svg",
    probHome: "55%",
    probDraw: "23%",
    probAway: "22%",
    xGHome: "2.40",
    xGAway: "1.70",
    recommendation: {
      market: "Over/Under",
      pick: "Over 3.0 Goals",
      odds: "1.75",
      probability: "79.0%",
      confidence: "High",
      type: "OU"
    },
    reasoning: "Kedua tim memimpin statistik shot-on-target per match di liga. Distribusi Poisson menunjukkan tren skor tinggi."
  },
  {
    id: 6,
    league: "French Ligue 1",
    time: "02:45 WIB",
    status: "Upcoming",
    homeTeam: "PSG",
    awayTeam: "Marseille",
    homeLogo: "https://crests.football-data.org/524.svg",
    awayLogo: "https://crests.football-data.org/516.svg",
    probHome: "62%",
    probDraw: "22%",
    probAway: "16%",
    xGHome: "2.35",
    xGAway: "0.85",
    recommendation: {
      market: "Asian Handicap",
      pick: "PSG -1.0",
      odds: "1.70",
      probability: "76.5%",
      confidence: "High",
      type: "HDP"
    },
    reasoning: "Selisih kualitas materi pemain dan performa laga kandang PSG yang mencatatkan kemenangan beruntun."
  },
  {
    id: 7,
    league: "Dutch Eredivisie",
    time: "19:30 WIB",
    status: "Upcoming",
    homeTeam: "PSV Eindhoven",
    awayTeam: "Ajax Amsterdam",
    homeLogo: "https://crests.football-data.org/674.svg",
    awayLogo: "https://crests.football-data.org/678.svg",
    probHome: "53%",
    probDraw: "25%",
    probAway: "22%",
    xGHome: "2.15",
    xGAway: "1.30",
    recommendation: {
      market: "1X2",
      pick: "Home Win (PSV)",
      odds: "1.78",
      probability: "73.0%",
      confidence: "Medium",
      type: "1X2"
    },
    reasoning: "PSV mencatatkan efisiensi pressing tertinggi di lini tengah yang menekan kreativitas serangan Ajax."
  },
  {
    id: 8,
    league: "English Premier League",
    time: "23:30 WIB",
    status: "Upcoming",
    homeTeam: "Liverpool",
    awayTeam: "Tottenham Hotspur",
    homeLogo: "https://crests.football-data.org/64.svg",
    awayLogo: "https://crests.football-data.org/73.svg",
    probHome: "60%",
    probDraw: "22%",
    probAway: "18%",
    xGHome: "2.50",
    xGAway: "1.20",
    recommendation: {
      market: "Asian Handicap",
      pick: "Liverpool -1.0",
      odds: "1.82",
      probability: "75.2%",
      confidence: "High",
      type: "HDP"
    },
    reasoning: "Rekor kandang Anfield dan intensitas serangan di 30 menit pertama menjadi faktor penentu utama."
  },
  {
    id: 9,
    league: "Portuguese Primeira Liga",
    time: "03:30 WIB",
    status: "Upcoming",
    homeTeam: "Benfica",
    awayTeam: "Sporting CP",
    homeLogo: "https://crests.football-data.org/1903.svg",
    awayLogo: "https://crests.football-data.org/498.svg",
    probHome: "39%",
    probDraw: "31%",
    probAway: "30%",
    xGHome: "1.40",
    xGAway: "1.35",
    recommendation: {
      market: "Over/Under",
      pick: "Under 2.5 Goals",
      odds: "1.92",
      probability: "70.5%",
      confidence: "Medium",
      type: "OU"
    },
    reasoning: "Derby ketat dengan fokus taktikal tinggi di lini tengah. Kedua tim memiliki statistik kebobolan terendah di liga."
  },
  {
    id: 10,
    league: "UEFA Europa League",
    time: "00:45 WIB",
    status: "Upcoming",
    homeTeam: "AS Roma",
    awayTeam: "Athletic Bilbao",
    homeLogo: "https://crests.football-data.org/100.svg",
    awayLogo: "https://crests.football-data.org/77.svg",
    probHome: "46%",
    probDraw: "30%",
    probAway: "24%",
    xGHome: "1.60",
    xGAway: "1.05",
    recommendation: {
      market: "1X2",
      pick: "Home Win (AS Roma)",
      odds: "1.95",
      probability: "71.8%",
      confidence: "Medium",
      type: "1X2"
    },
    reasoning: "AS Roma tampil dominan dalam laga eropa di kandang dengan efisiensi bola mati (*set-piece*) sebesar 28%."
  }
];
